#!/bin/bash

echo -n "Sisesta oma vanus: " #Küsib kasutaja vanust
read age #age - vanus

if [ $age -gt 0 -a $age -lt 11 ] #Number on 0 ja 11 vahel
then

	echo "Sa oled laps"
elif [ $age -ge 11 -a $age -lt 18 ] #Number on 11 ja 18 vahel
then
	echo "Sa oled nooruk"
elif [ $age -ge 18 -a $age -lt 63 ] #Number on 18 ja 63 vahel
then
	echo "Sa oled täiskasvanu"
elif [ $age -ge 63 ] #Number on üle 63
then
	echo "Sa oled seenior"
else
	echo "Error"#Vale sisendi puhul annab errori
fi
#Finish
