#!/bin/bash

#Kellaaeg
echo -n "Sisesta kellaaeg tunnina: "
read kell

#Kas on hommik?
if test $kell -ge 6 -a $kell -lt 12
then
	echo "Tere hommikust"

#Kas on päev?
elif test $kell -ge 12 -a $kell -lt 18
then
	echo "Tere päevast"

#Kas on õhtu?
elif test $kell -ge 18 -a $kell -lt 22
then
	echo "Tere õhtust"

#Kas on öö?
elif test $kell -ge 22 -a $kell -le 24 -o $kell -ge 0 -a $kell -lt 6
then
	echo "Head ööd"

#Kui on midagi muud sisestatud
else
	echo "Error"
fi
#Kõik

