#!/bin/bash
#

#Kas andmed on olemas?
if [ "$1" == "" ];then
	echo "Andmed puuduvad!"
#Loeb andmeid ja annab ühe kolmest vastusest
# 1 You pick up Unix
# 2 You pick up Linux
# Mingi muu arv = Error!
else
	if [ $1 -eq 1 ]
	then
		echo "You pick up Unix (Sun Os)"
	else
		if [ $1 -eq 2 ]
		then
			echo "You pick up Linux (Red Hat)"
		else
			echo "Error!"
		fi
	fi
fi
#Kolm fi'd lõpetab kolm if lauset.
#Finito
