#!/bin/bash
#Suvalise arvu sisestamine ja nende kokku liitmine

echo -n "Sisesta ükskõik mis täisarv: "
read arv
echo -n "Arvu $arv numbrite summa on "
#Kas on positiivne
if [ $arv -lt 0 ]; then
	 arv=$(($arv * -1))
	echo -n "-"
fi
#Summa arvutus
summa=0
while [ $arv -ne 0 ]
do
	jaak=$(($arv % 10))
	summa=$(($summa + $jaak))
	arv=$(($arv / 10))
done
echo "$summa"
#
#Skripti lõpp
