#! /bin/bash
#
#Sisend
echo -n "Sisetage kuu arv: "
read arv
#Väljund
echo -n "See kuu on "
#Väjund kaks
case $arv in
	"1") echo "jaanuar";;
	"2") echo "veebruar";;
	"3") echo "märts";;
	"4") echo "aprill";;
	"5") echo "mai";;
	"6") echo "juuni";;
	"7") echo "juuli";;
	"8") echo "august";;
	"9") echo "september";;
	"10") echo "okotoober";;
	"11") echo "november";;
	"12") echo "detsember";;
	*)echo "väär sisend";;
esac
#finito
