#! /bin/bash
#
#
echo -n "Sisesta suvaline arv: "
read arv
#Kas arv on 0 või 1
if [ $arv -eq 0 -o $arv -eq 1 ]
then
	echo $arv "ei ole tegemist algarvuga"
else 
#Defineerin jagaja ja jäägi
jag=2
jaak=$(($arv % $jag))
#while tsükkel
while [ $jaak -ne 0 ]
do
#Ühe võrra suurendamine ja jagamine
	jag=$(($jag + 1))
	jaak=$(($arv % $jag))
done
#Kontroll
if [ $arv -eq $jag ]
then
	echo $arv "on algarv"
else
	echo $arv "ei ole algarv"
fi
fi
#Finito
