#!/bin/bash
#
#yl2
#
echo -n "Sten Mumm, " #Minu nimi
echo -n "IS19, " #õppegrupp
echo -n "Väga huvitav aine, " #Aine kirjeldus
echo -n "peab hakkama saama" #edasijõudmine
echo  "!" #123321
#
#skripti lõpp
